on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: ./build-all.sh
    - name: Upload Binary
      uses: actions/upload-artifact@v1
      with:
        name: dist-release
        path: ./release
